spring:
  application:
    name: dubbo-registry-zookeeper-provider
#  main:
#    web-application-type: none
server:
  port: 8800
  servlet:
    context-path: /provider/hessian
dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    qos-enable: false
  protocols:
    dubbo: 
      name: dubbo
      port: 20880
#    hession:
#      name: hession
#      port: ${server.port}
#      server: servlet
#      contextpath: ${server.servlet.context-path}
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
    client: curator
  provider:
    validation: 1.0.0
    filter: validationFilter
    protocols:
    - dubbo
    - hessian
logging:
  level:
    root: info
    org.dante.spring.dubbo: debug