server:
  port: 8801
logging:
  level:
    root: info
    org.dante.spring.dubbo: debug
spring:
  dubbo:
    application:
      id: provider-test
      name: provider-test
      logger: slf4j
    server: true
    provider:
      filter: validationFilter
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol: 
      name: dubbo
      port: 20880      