server:
  port: 8801
logging:
  level:
    root: info
    org.dante.spring.dubbo: debug
spring:
  dubbo:
    application:
      id: provider-test
      name: provider-test
      logger: slf4j
    server: true
    provider:
      filter: validationFilter
    registry:
      address: zookeeper://spiritint-dubbo-zook.xiaohehe.com:31861
    protocol: 
      name: dubbo
      port: 20880      
      
#spring.dubbo.application.id=dubbo-Test
#spring.dubbo.application.name=dubbo-Test
#spring.dubbo.provider.filter=dubboLogFilter
#spring.dubbo.registry.address=zookeeper://127.0.0.1:2181
#spring.dubbo.server=true
#spring.dubbo.protocol.name=dubbo
#spring.dubbo.protocol.port=20880