spring:
  profiles:
    active: node1
#  main:
#    web-application-type: none
logging:
  level:
    root: info
    org.dante.spring.dubbo: debug
zk:
  address: 127.0.0.1:2181
#  address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
#  address: spirit-dubbo-zk.caas.poc.com:30012
---
spring:
  profiles: node1
server:
  port: 8800
  servlet:
    context-path: /provider/hessian
zk:
  dubbo: 20880
  hessian: 8800
  qos: 22222

---
spring:
  profiles: node2
server:
  port: 8801
zk:
  dubbo: 20881
  hessian: 8801
  qos: 22223