spring:
  application:
    name: dubbo-registry-zookeeper-provider
server:
  port: 8082
logging:
  level:
    root: info
    org.dante.spring.dubbo: debug
dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    qos-enable: false
  consumer:
    version: 1.0.0
    timeout: 3000
    retries: 2
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
    client: curator