server:
  port: 8802
logging:
  level:
    root: info
    org.dante.spring.dubbo: debug
spring:
  dubbo:
    application:
      id: consumer-test-2
      name: consumer-test-2
      logger: slf4j
      qos:
        port: 22223
    registry: 
      address: zookeeper://127.0.0.1:2181
    consumer:
      check: false
    reference:
      check: false