server:
  port: 8802
logging:
  level:
    root: info
    org.dante.spring.dubbo: debug
zk:
#  address: 127.0.0.1:2181
  address: spirit-dubbo-zk.caas.poc.com:30012
  appName: consumer-test-1
  qosPort: 2223